USE [master]
GO
/****** Object:  Database [EmployeeManagement_db]    Script Date: 10/20/2018 9:20:00 AM ******/
CREATE DATABASE [EmployeeManagement_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeManagement_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EmployeeManagement_db.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EmployeeManagement_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EmployeeManagement_db_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [EmployeeManagement_db] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeManagement_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EmployeeManagement_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EmployeeManagement_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EmployeeManagement_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EmployeeManagement_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EmployeeManagement_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EmployeeManagement_db] SET  MULTI_USER 
GO
ALTER DATABASE [EmployeeManagement_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EmployeeManagement_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EmployeeManagement_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EmployeeManagement_db] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [EmployeeManagement_db] SET DELAYED_DURABILITY = DISABLED 
GO
USE [EmployeeManagement_db]
GO
/****** Object:  Table [dbo].[Cities]    Script Date: 10/20/2018 9:20:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cities](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](55) NOT NULL,
	[CountryId] [int] NOT NULL,
 CONSTRAINT [PK_Cities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Countries]    Script Date: 10/20/2018 9:20:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Countries](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](55) NOT NULL,
 CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Employees]    Script Date: 10/20/2018 9:20:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](55) NOT NULL,
	[Email] [nvarchar](55) NOT NULL,
	[Salary] [float] NOT NULL,
	[CityId] [int] NOT NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Cities]  WITH CHECK ADD  CONSTRAINT [FK_Cities_Countries] FOREIGN KEY([CountryId])
REFERENCES [dbo].[Countries] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Cities] CHECK CONSTRAINT [FK_Cities_Countries]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [FK_Employees_Cities] FOREIGN KEY([CityId])
REFERENCES [dbo].[Cities] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [FK_Employees_Cities]
GO
USE [master]
GO
ALTER DATABASE [EmployeeManagement_db] SET  READ_WRITE 
GO
